# Generated by Django 4.2.4 on 2023-10-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('genery', models.CharField(max_length=255)),
                ('pg', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=255)),
                ('qtd', models.IntegerField()),
                ('name_sacado', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
