# Generated by Django 4.2.4 on 2023-11-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0003_alter_livro_genery_alter_livro_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='emprestado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
