# Generated by Django 4.2.4 on 2023-11-23 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0001_initial'),
        ('bibliotecaApp', '0004_livro_emprestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
