# Generated by Django 4.2.4 on 2023-11-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0005_livro_empresa_livro_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='emprestado',
            field=models.IntegerField(default=0),
        ),
    ]
