# Generated by Django 4.2.4 on 2023-12-01 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0006_alter_livro_emprestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='name_sacado',
        ),
    ]
