# Generated by Django 4.2.4 on 2023-12-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0008_genero_empresa_genero_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='cod',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
