# Generated by Django 4.2.4 on 2023-12-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0009_genero_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
