# Generated by Django 4.2.4 on 2023-11-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_emprestimo_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='qtd_livros',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
