# Generated by Django 4.2.4 on 2023-11-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_qtd_livros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='cod',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
