# Generated by Django 4.2.4 on 2023-12-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_emprestimo_devolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='dias_para_devolver',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
