# Generated by Django 4.2.4 on 2023-12-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_remove_emprestimo_devolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='saldo_de_dias_devolvidos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
