# Generated by Django 4.2.4 on 2023-11-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargos',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
    ]
